### ISSUE TITLE
Can not add task

### ISSUE THREAD

**Issue by erdemsusam** [bluecolor/octopus#17]
Created connection Local.

When try to add new task, return an error message:

Resolved exception caused by Handler execution: org.springframework.http.converter.HttpMessageNotWritableException: Could not write content: (was java.lang.NullPointerException) (through reference chain: io.octopus.model.Task["owners"]->org.hibernate.collection.internal.PersistentSet[0]->io.octopus.model.User["stats"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: io.octopus.model.Task["owners"]->org.hibernate.collection.internal.PersistentSet[0]->io.octopus.model.User["stats"])

**Comment by ceyhunkerti** [comment]
fixed https://github.com/bluecolor/octopus/commit/698883ad4eb4e916c9f9d6b79983a8726efc6756
