### ISSUE TITLE
Loading tasks page spin infinitely

### ISSUE THREAD

**Issue by erdemsusam** [bluecolor/octopus#18]
After adding a task, clicking Task icon lead to loading icon spin infinitely and not load page.

**Comment by ceyhunkerti** [comment]
This generally happens when your session is expired. [this](https://github.com/bluecolor/octopus/commit/6888aca2a663460f27ce8e9f9ecc19ea2d7f0f73) will redirect to logout when session expired.

Please reload the page and try again. btw. is the Task icon the menu item with the gear in side bar?

**Comment by erdemsusam** [comment]
Yes gear icon in the sidebar. I tried reloading many times, logged out and in again but still spinning.

**Comment by ceyhunkerti** [comment]
what does the browser logs say ? see the console
ctr+shift+i or f12

**Comment by ceyhunkerti** [comment]
I guess it  happens when a task created without group primary group.
[that](https://github.com/bluecolor/octopus/commit/e992a3ef982084171c27bd86ffaf5a6a8cc2558d) should fix this issue
